### ISSUE TITLE
Fixa todos

### ISSUE THREAD

**Issue by gustafc** [gustafc/mestro-git-workshop#2]
I repot finns fem olika filer med varsin TODO som ska fixas. Så här är arbetsfördelningen:

LengthProcessor - @mestromagnus fixar TODOn i denna fil
LowerCaseProcessor - @fresni 
ReverseProcessor - @grapplerXcross 
TrimmingProcessor - @Sesdun 
UpperCaseProcessor - @Tinrak 

Gör på följande sätt:
- Checka ut en ny branch som heter t.ex. `dev_fix_todo_DITTNAMN`
- Fixa din TODO och kolla att testerna går igenom
- Pusha din nya branch till github
- Gör en pull request och tilldela den till personen under dig i lista (Magnus skickar till Fredrik, Fredrik till Petter, etc)

När du själv får en PR, gör så här:
- Gör `git pull` och checka ut motsvarande branch med `git checkout branchensnamn`
- Kolla att testerna går igenom
- Om allt är OK, merge in PRen i Github och ge en :+1: eller möjligt :hand: till din kollega.

**Comment by gustafc** [comment]
Ping @Tinrak min Skype är rätt död, förstår du instruktionerna?

**Comment by Tinrak** [comment]
Copy that!

**Comment by gustafc** [comment]
Då så, alla TODOs fixade och workshop avklarad. Well done :+1: :smile_cat:
